config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :friends_tables
  get 'home/index'
  get 'home/about'
  root 'home#index'
  resources :conversations, only: [:create] do
    member do
      post :close
    end
  end
  resources :messages, only: [:create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/conversation.rb
class Conversation < ApplicationRecord
    has_many :messages, dependent: :destroy
    belongs_to :sender, foreign_key: :sender_id, class_name: 'User'
    belongs_to :recipient, foreign_key: :recipient_id, class_name: 'User'
  
    validates :sender_id, uniqueness: { scope: :recipient_id }
  
    scope :between, -> (sender_id, recipient_id) do
      where(sender_id: sender_id, recipient_id: recipient_id).or(
        where(sender_id: recipient_id, recipient_id: sender_id)
      )
    end
  
    def self.get(sender_id, recipient_id)
      conversation = between(sender_id, recipient_id).first
      return conversation if conversation.present?
  
      create(sender_id: sender_id, recipient_id: recipient_id)
    end
  
    def opposed_user(user)
      user == recipient ? sender : recipient
    end
end

app/models/friends_table.rb
class FriendsTable < ApplicationRecord
    belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :conversation
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :friends_table
         has_many :messages
         has_many :conversations, foreign_key: :sender_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
    def create
      @conversation = Conversation.get(current_user.id, params[:user_id])
      
      add_to_conversations unless conversated?
  
      respond_to do |format|
        format.js
      end
    end
    def close
        @conversation = Conversation.find(params[:id])
    
        session[:conversations].delete(@conversation.id)
    
        respond_to do |format|
          format.js
        end
      end
    private
  
    def add_to_conversations
      session[:conversations] ||= []
      session[:conversations] << @conversation.id
    end
  
    def conversated?
      session[:conversations].include?(@conversation.id)
    end
  end

app/controllers/friends_tables_controller.rb
class FriendsTablesController < ApplicationController
  before_action :set_friends_table, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except:[:index,:show]
  before_action :correct_user, only: [:edit, :update,:destroy]
  # GET /friends_tables or /friends_tables.json
  def index
    @friends_tables = FriendsTable.all
  end

  # GET /friends_tables/1 or /friends_tables/1.json
  def show
  end

  # GET /friends_tables/new
  def new
    @friends_table = current_user.friends_table.build
  end

  # GET /friends_tables/1/edit
  def edit
  end

  def correct_user
    @friends_table = current_user.friends_table.find_by(id: params[:id])
    redirect_to friends_tables_path, notice:"Not Authorized to edit this friend" if @friends_table.nil?
  end

  # POST /friends_tables or /friends_tables.json
  def create
    #@friends_table = FriendsTable.new(friends_table_params)
    @friends_table = current_user.friends_table.build(friends_table_params)
    respond_to do |format|
      if @friends_table.save
        format.html { redirect_to @friends_table, notice: "Friends table was successfully created." }
        format.json { render :show, status: :created, location: @friends_table }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friends_table.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends_tables/1 or /friends_tables/1.json
  def update
    respond_to do |format|
      if @friends_table.update(friends_table_params)
        format.html { redirect_to @friends_table, notice: "Friends table was successfully updated." }
        format.json { render :show, status: :ok, location: @friends_table }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friends_table.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends_tables/1 or /friends_tables/1.json
  def destroy
    @friends_table.destroy
    respond_to do |format|
      format.html { redirect_to friends_tables_url, notice: "Friends table was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friends_table
      @friends_table = FriendsTable.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friends_table_params
      params.require(:friends_table).permit(:first_name, :last_name, :email, :phone, :twitter)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    session[:conversations] ||= []

    @users = User.all.where.not(id: current_user)
    @conversations = Conversation.includes(:recipient, :messages)
                                 .find(session[:conversations])
  end
  def about
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @conversation = Conversation.includes(:recipient)
      .find(params[:message][:conversation_id])
    @message = @conversation.messages.create(message_params)

    respond_to do |format|
      format.js
    end
  end

  private

  def message_params
    params.require(:message).permit(:user_id, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_tables_helper.rb
module FriendsTablesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/conversations/_conversation.html.erb
<li>
  <div class="panel panel-default" data-conversation-id="<%= conversation.id %>">
    <div class="panel-heading">
      <%= link_to conversation.opposed_user(user).email, '', class: 'toggle-window' %>
      <%= link_to "x", close_conversation_path(conversation), class: "btn btn-default btn-xs pull-right", remote: true, method: :post %>
    </div>

    <div class="panel-body" style="display: none;">
      <div class="messages-list">
        <ul>
          <%= render 'conversations/conversation_content', messages: conversation.messages, user: user %>
        </ul>
      </div>
     <form class="new_message">
        <input name="conversation_id" type="hidden" value="<%= conversation.id %>">
        <input name="user_id" type="hidden" value="<%= user.id %>">
        <textarea name="body" class="form-control"></textarea>
        <input type="submit" class="btn btn-success" value="Send">
      </form>
    </div>
  </div>
</li>

app/views/conversations/_conversation_content.html.erb
<% messages.each do |message| %>
  <%= render message, user: user %>
<% end %>

app/views/conversations/close.js.erb
$('#conversations-list').find("[data-conversation-id='" + "<%= @conversation.id %>" + "']").parent().remove();

app/views/conversations/create.js.erb
var conversations = $('#conversations-list');
var conversation = conversations.find("[data-conversation-id='" + "<%= @conversation.id %>" + "']");

if (conversation.length !== 1) {
  conversations.append("<%= j(render 'conversations/conversation', conversation: @conversation, user: current_user) %>");
  conversation = conversations.find("[data-conversation-id='" + "<%= @conversation.id %>" + "']");
}

conversation.find('.panel-body').show();

var messages_list = conversation.find('.messages-list');
var height = messages_list[0].scrollHeight;
messages_list.scrollTop(height);

app/views/friends_tables/_form.html.erb
<%= form_with(model: friends_table) do |form| %>
  <% if friends_table.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(friends_table.errors.count, "error") %> prohibited this friends_table from being saved:</h2>

      <ul>
        <% friends_table.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field from-group">
    <%= form.label :first_name %>
    <%= form.text_field :first_name,
    class:"form-control" %>
  </div>

  <div class="field from-group">
    <%= form.label :last_name %>
    <%= form.text_field :last_name,
    class:"form-control" %>
  </div>

  <div class="field from-group">
    <%= form.label :email %>
    <%= form.text_field :email,
    class:"form-control" %>
  </div>

  <div class="field from-group">
    <%= form.label :phone %>
    <%= form.text_field :phone,
    class:"form-control" %>
  </div>

  <div class="field from-group">
    <%= form.label :twitter %>
    <%= form.text_field :twitter,
    class:"form-control" %>
  </div>
  
  <div class="actions">
    <%= form.submit class:"btn btn-primary" %>
  </div>
<% end %>

app/views/friends_tables/edit.html.erb
<h1>Editing Friends Table</h1>

<%= render 'form', friends_table: @friends_table %>

<%= link_to 'Show', @friends_table %> |
<%= link_to 'Back', friends_tables_path %>

app/views/friends_tables/index.html.erb
<h1>Friends Tables</h1>
<table class="table table-striped table-bordered table-hover">
    <thead class="table-dark">
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Twitter</th>
      <th>Owner</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @friends_tables.each do |friends_table| %>
      <tr>
        <td><%= friends_table.first_name %></td>
        <td><%= friends_table.last_name %></td>
        <td><%= friends_table.email %></td>
        <td><%= friends_table.phone %></td>
        <td><%= friends_table.twitter %></td>
        <td><%= friends_table.user_id %></td>
        <td><%= link_to 'Show', friends_table %></td>
        <td><%= link_to 'Edit', edit_friends_table_path(friends_table) %></td>
        <td><%= button_to 'Destroy', friends_table, :method => :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Friend', new_friends_table_path,class:"btn btn-secondary" %>

app/views/friends_tables/new.html.erb
<h1>New Friends Table</h1>

<%= render 'form', friends_table: @friends_table %>

<%= link_to 'Back', friends_tables_path %>

app/views/friends_tables/show.html.erb
<div class="p-5 mb-4 bg-light border rounded-3">
      <div class="container-fluid py-5">
        <h1 class="display-5 fw-bold"><%= @friends_table.first_name %>  <%= @friends_table.last_name %></h1>
        <p class="col-md-8 fs-4"><%= @friends_table.email %> | <%= @friends_table.phone %> | <%= @friends_table.twitter %></p>
        <br/>
        <hr/>
        <%= link_to 'Edit', edit_friends_table_path(@friends_table),class:"btn btn-secondary" %> 
        <%= link_to 'Back', friends_tables_path ,class:"btn btn-secondary"%>
      </div>
    </div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "Friend App",root_path,class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "About us", home_about_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Friends", friends_tables_path, class:"nav-link" %>
        </li>
      
        <% if user_signed_in?%>
          <li class="nav-item">
            <%= link_to "Add Friend", new_friends_table_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Edit Profile", edit_user_registration_path, class:"nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign In", user_session_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign Up", new_user_registration_path, class:"nav-link" %>
          </li>
        <% end %>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
This is about...

app/views/home/index.html.erb
<div class="row">
  <div class="col-md-9">
    <ul id="conversations-list">
    <h1><%= @conversations.length%></h1>
      <% @conversations.each do |conversation| %>
        <%=render 'conversations/conversation', conversation: conversation, user: current_user %>
      <% end %>
    </ul>
  </div>

  <div class="col-md-3">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title">User list</h3>
      </div>
      <div class="panel-body">
        <ul>
          <% @users.each do |user| %>
            <li><%= link_to user.email, conversations_path(user_id: user), remote: true, method: :post %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_alert.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">

    <title>Friends App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>
  <body>
    <%= render "home/header" %>
    <div class = "container">
      <% if notice %>
        <%= render "layouts/alert" %>
      <%end%>
      <br/>
      <%= yield %>
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-W8fXfP3gkOKtndU4JGtKDvXbO53Wy8SZCQHczT5FMiiqmQfUpWbYdTil/SxwZgAN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.min.js" integrity="sha384-skAcpIdS7UcVUC05LJ9Dxay8AXcDYfBJqt1CJ85S/CFujBsIzCIv+l9liuYLaMQ/" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/messages/_message.html.erb
<li>
  <div class="row">
    <div class="<%= user.id == message.user_id ? 'message-sent' : 'message-received' %>">
      <%= message.body %>
    </div>
  </div>
</li>

app/views/messages/create.js.erb
var conversation = $('#conversations-list').find("[data-conversation-id='" + "<%= @conversation.id %>" + "']");
conversation.find('.messages-list').find('ul').append("<%= j(render 'messages/message', message: @message, user: current_user) %>");
conversation.find('textarea').val('');